version: '3'
services:
  config-service-client:
    image: example/config-service-client
    depends_on:
      - config-service
    ports:
      - "8080:8080"
    environment:
      SPRING_CLOUD_CONFIG_URI: http://config-service:8888
      SPRING_CLOUD_CONFIG_ENABLED: "true"
      SPRING_CLOUD_CONFIG_TOKEN: s.6zlOlGmCDv0CAm7YueQD7vVJ
  config-service:
    image: example/config-service
    ports:
      - "8888:8888"
    depends_on:
      - vault-populator
    environment:
      SPRING_CLOUD_CONFIG_SERVER_GIT_URI: file://config-repo
      SPRING_CLOUD_CONFIG_SERVER_VAULT_HOST: vault
    volumes:
      - "${HOME}/config-repo:/config-repo"
  vault:
    image: vault
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=roottoken
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
      - VAULT_TOKEN=roottoken
  vault-populator:
    image: vault
    depends_on:
      - vault
    cap_add:
      - IPC_LOCK
    environment:
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=roottoken
    volumes:
      - "./vault/policies:/policies"
    command: >
      sh -c "vault policy write config-service-client-policy /policies/config-service-client-policy.hcl &&
      vault token create -policy=config-service-client-policy &&
      vault kv put secret/config-service-client config.name=secret"
