version: '3'
services:
  config-service:
    image: example/config-service
    ports:
      - "8888:8888"
    environment:
      SPRING_CLOUD_CONFIG_SERVER_GIT_URI: file://config-repo
      SPRING_CLOUD_CONFIG_SERVER_VAULT_HOST: vault
    volumes:
      - "/Users/leafarmer/config-repo:/config-repo"
  vault:
    image: vault
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=roottoken
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
      - VAULT_TOKEN=roottoken
